version: "3.4"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022
    volumes:
      - /array/media/plex/config:/config
      - /array/media/plex/Tv:/Tv
      - /array/media/plex/Movies:/Movies
    restart: unless-stopped
  deluge-vpn:
    image: sgtsquiggs/deluge-openvpn
    container_name: "deluge-vpn"
    env_file:
      - .vpn
    volumes:
      - /array/media/deluge/config:/config
      - /array/media/plex:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8112:8112"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - TZ=Pacific/Auckland
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_CONFIG=nz32.nordvpn.com.tcp
      - LOCAL_NETWORK=192.168.0.0/16
      - DELUGE_LOGLEVEL=error
    devices:
      - dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - /array/media/jackett/config:/config
      - /array/media/plex:/downloads
    ports: 
      - "9117:9117"
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
      - UMASK_SET=022
    volumes:
      - /array/media/sonarr/config:/config
      - /array/media/plex/Tv:/tv
      - /array/media/plex:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
      - UMASK_SET=022
    volumes:
      - /array/media/radarr/config:/config
      - /array/media/plex/Movies:/movies
      - /array/media/plex:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - /array/media/ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped
