version: "3.4"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022
    volumes:
      - /media/plex/config:/config
      - /media/plex/Tv:/Tv
      - /media/plex/Movies:/Movies
    restart: unless-stopped
  deluge-vpn:
    image: sgtsquiggs/deluge-openvpn
    container_name: "deluge-vpn"
    env_file:
      - .vpn
    volumes:
      - /media/deluge/config:/config
      - /media:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8112:8112"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - TZ=Pacific/Auckland
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_CONFIG=al10.nordvpn.com.tcp
      - LOCAL_NETWORK=192.168.0.0/16
      - DELUGE_LOGLEVEL=error
    devices:
      - dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

