version: "2"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=113
      - PGID=113
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
    volumes:
      - /media/plex/config:/config
      - /media/plex/Tv:/tv
      - /media/plex/Movies:/movies
    restart: unless-stopped
    ports:
      - 32400:32400
