version: "3.4"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
    volumes:
      - /media/plex/config:/config
      - /media/plex/Tv:/Tv
      - /media/plex/Movies:/Movies
    restart: unless-stopped
